name: Release SecretHound

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        
      - name: Build for all platforms
        run: |
          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -ldflags "-X github.com/rafabd1/SecretHound/cmd.Version=${{ env.VERSION }}" -o secrethound-${{ env.VERSION }}-windows-amd64.exe ./cmd/secrethound/
          
          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -ldflags "-X github.com/rafabd1/SecretHound/cmd.Version=${{ env.VERSION }}" -o secrethound-${{ env.VERSION }}-linux-amd64 ./cmd/secrethound/
          
          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/rafabd1/SecretHound/cmd.Version=${{ env.VERSION }}" -o secrethound-${{ env.VERSION }}-darwin-amd64 ./cmd/secrethound/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: SecretHound v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            secrethound-${{ env.VERSION }}-windows-amd64.exe
            secrethound-${{ env.VERSION }}-linux-amd64
            secrethound-${{ env.VERSION }}-darwin-amd64
          body: |
                # SecretHound v${{ env.VERSION }}
                
                ## Improvements
                
                - Added support for ignoring SSL/TLS certificate verification with `--insecure`
                - Complete overhaul of the regex pattern system
                - Added support for custom HTTP headers with `-H/--header`
                - Fixed timeout and concurrency issues
                - Fixed `-r/--retries` parameter that wasn't being applied
                - Reorganized patterns package for better maintenance
                - Redesigned error handling system
                - Temporarily disabled `--regex-file` option
                
                ## Bug Fixes
                
                - Fixed issue with URLs having invalid certificates
                - Resolved timeout problems in large scans
                - Improved synchronization between threads to prevent resource leaks
                - Fixed false positive issues in certain regex patterns
                
                ## Installation
                
                Download the appropriate binary for your platform and make it executable.
                
                For Linux/macOS:
                ```
                chmod +x secrethound-${{ env.VERSION }}-linux-amd64
                ./secrethound-${{ env.VERSION }}-linux-amd64
                ```
                
                For Go users:
                ```
                go install github.com/rafabd1/SecretHound/cmd/secrethound@latest
                ```
                
                ## Documentation
                
                See the [documentation](https://github.com/rafabd1/SecretHound/tree/main/docs) for usage details.